### ISSUE TITLE
what's the runDeFA in  test.m line 37 ?

### ISSUE THREAD

**Issue by Guyume** [yaojieliu/ICCVW2017-DenseFaceAlignment#2]
I run the test.m in matlab2018b, with complied matconvnet cpu, but it show me the error

`未定义函数或变量 'runDeFA'。

出错 test (line 37)
[A3D,landmark68] = runDeFA(im,DeFA)`

and I didn't find any function or document named runDeFA, can you help me or tell me what's it mean?
thx

**Comment by ne-bo** [comment]
I've found a function runDeFa here
matlab/runDeFA.m
But it doesn't work for me .
I get the error:
error: invalid use of script /home/pavlovskaya/Downloads/ICCVW2017-DenseFaceAlignment-master/matlab/vl_nnconv.m in index expression
error: called from
    vl_test_simplenn at line 297 column 14
    runDeFA at line 18 column 5
    test at line 38 column 17

But in the file  vl_test_simplenn.m we have at line 297 exacltly basic computing of the outputs:
output = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
        'pad', l.pad, ...
        'stride', l.stride, ...
        l.opts{:}, ...
        cudnn{:}) ;

I don't understand what is wrong here with the index expression.
 Unfortunately I'm not proficient in matlab, so I wanted just use this code as a blackbox to get 3D map of the face. But can't even run the script on the test image(((

**Comment by Guyume** [comment]
> I've found a function runDeFa here
> matlab/runDeFA.m
> But it doesn't work for me .
> I get the error:
> error: invalid use of script /home/pavlovskaya/Downloads/ICCVW2017-DenseFaceAlignment-master/matlab/vl_nnconv.m in index expression
> error: called from
> vl_test_simplenn at line 297 column 14
> runDeFA at line 18 column 5
> test at line 38 column 17
> 
> But in the file vl_test_simplenn.m we have at line 297 exacltly basic computing of the outputs:
> output = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
> 'pad', l.pad, ...
> 'stride', l.stride, ...
> l.opts{:}, ...
> cudnn{:}) ;
> 
> I don't understand what is wrong here with the index expression.
> Unfortunately I'm not proficient in matlab, so I wanted just use this code as a blackbox to get 3D map of the face. But can't even run the script on the test image(((

thx, I find it, because I replaced the original matlab file with the one I compiled, and the compiled one has no runDeFA.mat. And now it works.
I downloaded the matconvnet , compiled it and raplaced the original matlab with compiled matconvnet's matlab file, then it works ,  you can have a try i think

**Comment by yaojieliu** [comment]
I close this issue since it's solved.
